baseURL = 'https://tinytapeout.com'
locale = 'en-US'
title = 'Tiny Tapeout'
theme = ["learn", "hugo-shortcode-gallery"]
enableGitInfo = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^CF_']

[[menu.shortcuts]]
  name = "<i class='fa fa-shopping-basket'></i> Store"
  url = "https://store.tinytapeout.com/"

[markup.goldmark.renderer]
  unsafe= true

[params]
  Description = "Quicker, easier and cheaper than ever to make your own chip!"
  themeVariant = "tinytapeout"
  defaultContentLanguage = 'en'
  disableLightbox = true
  workshopFeedbackLink = "https://docs.google.com/forms/d/e/1FAIpQLSelFOYEZ7mXMm2zVuQYh2mu494tdsgndyf-7d7eUubWDvoKOw/viewform?usp=header"
  workshopFoundry = "sky"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
  [Languages.en]
    title = "Quicker, easier and cheaper to make your own chip!"
    weight = 1
    label = "English"

  [Languages.es]
    title = "¡Hacer tu propio chip de forma más rápida, más fácil y más barata!"
    weight = 2
    label = "Español"
    disabled = true

  [Languages.ua]
    title = "Документація українською"
    weight = 3
    label = "Українська"
    disabled = true

  [Languages.it]
    title = "Crea il tuo microchip in modo più veloce, più semplice ed economico!"
    weight = 4
    label = "Italiano"
    disabled = true
