baseURL = 'https://tinytapeout.com'
locale = 'en-US'
title = 'Tiny Tapeout'
theme = ["learn", "hugo-shortcode-gallery"]
enableGitInfo = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^CF_']

[[menu.shortcuts]]
  name = "<i class='fa fa-shopping-basket'></i> Store"
  url = "https://store.tinytapeout.com/"

[markup.goldmark.renderer]
  unsafe= true

[params]
  Description = "Quicker, easier and cheaper than ever to make your own chip!"
  themeVariant = "tinytapeout"
  defaultContentLanguage = 'en'
  disableLightbox = true
  workshopFeedbackLink = "https://docs.google.com/forms/d/e/1FAIpQLSeVc9YmYN5TYKsDpFGyPtZE6N3sstT2PcbTdee-bK8FMjQwEQ/viewform?usp=header"
  workshopFoundry = "sky"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
  [Languages.en]
    title = "Quicker, easier and cheaper to make your own chip!"
    weight = 1
    label = "English"

  [Languages.es]
    title = "¡Hacer tu propio chip de forma más rápida, más fácil y más barata!"
    weight = 2
    label = "Espa\u00f1ol"

  [Languages.ua]
    title = "Документація українською"
    weight = 3
    label = "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430"

  [Languages.it]
    title = "Crea il tuo microchip in modo piÃ¹ veloce, piÃ¹ semplice ed economico!"
    weight = 4
    label = "Italiano"

#disableLanguages = ['es', 'it']
